### ISSUE TITLE
I don't see any hyphens in my book (kindle voyage with latest software)

### ISSUE THREAD

**Issue by purpleP** [dmalinovsky/kindle-hyphens#6]
I've ran your main.py on my fb2 book and then converted it to mobi via web service. Then I've sent to kindle via email (I don't know what actual steps matter) and I don't see any hyphens.

**Comment by dmalinovsky** [comment]
You'll have to convert it to `mobi` yourself, most likely this service is converting it into old style `mobi` v6, you need to use newer [KF8](https://en.wikipedia.org/wiki/Amazon_Kindle#File_formats).  Easy way to do it is via Amazon's [`kindlegen`](https://www.amazon.com/gp/feature.html?docId=1000765211) command line program, which accepts `*.fb2.zip` file as input (it should be hyphenated already), and produces `.mobi` with both v6 and v8 parts.  You can send generated file to your `@kindle.com` mailbox to get it delivered to your device, or you can use USB cable to transfer to your device directly.
